=== radinan/XML/anime_catalog.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT anime_catalog (anime*)>
    <!ELEMENT anime (main_info, show_info, publish_info, statistics_info)>
        <!ELEMENT main_info (title, author, genre, type, source)>
            <!ELEMENT title (#PCDATA)>
            <!ELEMENT author (#PCDATA)>
            <!ELEMENT genre (#PCDATA)>
            <!ELEMENT type (#PCDATA)>
            <!ELEMENT source (#PCDATA)>
        <!ELEMENT show_info (seasons+, all_episodes, duration)>
            <!ELEMENT seasons (season+)>
                <!ELEMENT season (#PCDATA)>
            <!ELEMENT all_episodes (#PCDATA)>
            <!ELEMENT duration (#PCDATA)>
        <!ELEMENT publish_info (aired, premiered, studio, producers, licensors)>
            <!ELEMENT aired (begin, end)>
                <!ELEMENT begin (#PCDATA)>
                <!ELEMENT end (#PCDATA)>
            <!ELEMENT premiered (#PCDATA)>
            <!ELEMENT studio (#PCDATA)>
            <!ELEMENT producers (#PCDATA)>
            <!ELEMENT licensors (#PCDATA)>
        <!ELEMENT statistics_info (score, rank, popularity)>
            <!ELEMENT score (#PCDATA)>
            <!ELEMENT rank (#PCDATA)>
            <!ELEMENT popularity (#PCDATA)>

<!ATTLIST anime anime_id CDATA #REQUIRED>
<!ATTLIST anime is_going (Да|Не) "Да">
<!ATTLIST season episodes CDATA #REQUIRED>
<!ATTLIST season period CDATA #REQUIRED>
<!ATTLIST duration unit CDATA #REQUIRED>
<!ATTLIST premiered unit CDATA #REQUIRED>
<!ATTLIST premiered season (Winter|Spring|Summer|Fall) #REQUIRED>

=== radinan/XML/valid_xml_2.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE anime_catalog SYSTEM "anime_catalog.dtd">

<anime_catalog>
    <anime anime_id="2">
        <main_info>
            <title>Naruto Shippuden</title>
            <author nationality="Japanese">Masashi Kishimoto</author>
            <genre>Action, Adventure, Comedy</genre>
            <type>Shounen</type>
            <source>Manga</source>
        </main_info>
        <show_info>
            <seasons>
                <season episodes="32">1</season>
                <season episodes="21">2</season>
                <season episodes="18">3</season>
                <season episodes="17">4</season>
                <season episodes="24">5</season>
                <season episodes="31">6</season>
                <season episodes="8">7</season>
                <season episodes="24">8</season>
                <season episodes="21">9</season>
                <season episodes="25">10</season>
                <season episodes="21">11</season>
                <season episodes="33">12</season>
                <season episodes="20">13</season>
                <season episodes="25">14</season>
                <season episodes="28">15</season>
                <season episodes="13">16</season>
                <season episodes="11">17</season>
                <season episodes="21">18</season>
                <season episodes="20">19</season>
                <season episodes="66">20</season>
                <season episodes="21">21</season>
            </seasons>
            <all_episodes>500</all_episodes>
            <duration unit="minutes">23</duration>
        </show_info>
        <publish_info>
            <aired>
                <begin>15 Feb 2007</begin>
                <end>23 Mar 2017</end>
            </aired>
            <premiered season="Winter">2007</premiered>
            <studio>Studio Pierrot</studio>
            <producers>TV Tokyo, Aniplex, KSS, Rakuonsha, TV Tokyo Music, Shueisha</producers>
            <licensors>VIZ Media</licensors>
        </publish_info>
        <statistics_info>
            <score>8.23</score>
            <rank>288</rank>
            <popularity>16</popularity>
        </statistics_info>
    </anime>
</anime_catalog>

=== radinan/XML/valid_xml_3.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE anime_catalog SYSTEM "anime_catalog.dtd">

<anime_catalog>
    <anime anime_id="3">
        <main_info>
            <title>Odd Taxi</title>
            <author nationality="Japanese">Kazuya Konomoto, Takeichi Abaraya</author>
            <genre>Mystery</genre>
            <type>Seinen</type>
            <source>Original</source>
        </main_info>
        <show_info>
            <seasons>
                <season episodes="13">1</season>
            </seasons>
            <all_episodes>13</all_episodes>
            <duration unit="minutes">23</duration>
        </show_info>
        <publish_info>
            <aired>
                <begin>6 Apr 2021</begin>
                <end>29 Jun 2021</end>
            </aired>
            <premiered season="Spring">2021</premiered>
            <studio>OLM, P.I.C.S.</studio>
            <producers>Pony Canyon, Pony Canyon Enterprise</producers>
            <licensors>Unknown</licensors>
        </publish_info>
        <statistics_info>
            <score>8.77</score>
            <rank>36</rank>
            <popularity>840</popularity>
        </statistics_info>
    </anime>
</anime_catalog>

=== radinan/XML/valid_xml_5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE anime_catalog SYSTEM "anime_catalog.dtd">

<anime_catalog>
    <anime anime_id="5" is_going="Да">
        <main_info>
            <title>Koroshi Ai</title>
            <author>Fe</author>
            <genre>Action, Romance</genre>
            <type>Josei</type>
            <source>Manga</source>
        </main_info>
        <show_info>
            <seasons>
                <season episodes="4" period="2022">1</season>
            </seasons>
            <all_episodes>12</all_episodes>
            <duration unit="minutes">23</duration>
        </show_info>
        <publish_info>
            <aired>
                <begin>13 Jan 2022</begin>
                <end>Unknown</end>
            </aired>
            <premiered unit="year" season="Winter">2022</premiered>
            <studio>Platinum Vision</studio>
            <producers>Pony Canyon</producers>
            <licensors>Crunchyroll</licensors>
        </publish_info>
        <statistics_info>
            <score>7.03</score>
            <rank>3715</rank>
            <popularity>1972</popularity>
        </statistics_info>
    </anime>
</anime_catalog>

=== radinan/XML/valid_xml_4.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE anime_catalog SYSTEM "anime_catalog.dtd">

<anime_catalog>
    <anime anime_id="4" is_going="ะะต">
        <main_info>
            <title>Tokyo Revengers</title>
            <author>Ken Wakui</author>
            <genre>Action, Drama, Supernatural</genre>
            <type>Shounen</type>
            <source>Manga</source>
        </main_info>
        <show_info>
            <seasons>
                <season episodes="13" period="2021">1</season>
            </seasons>
            <all_episodes>13</all_episodes>
            <duration unit="minutes">23</duration>
        </show_info>
        <publish_info>
            <aired>
                <begin>11 Apr 2021</begin>
                <end>19 Sep 2021</end>
            </aired>
            <premiered unit="year" season="Spring">2021</premiered>
            <studio>LIDENFILMS</studio>
            <producers>Pony Canyon</producers>
            <licensors>Unknown</licensors>
        </publish_info>
        <statistics_info>
            <score>8.24</score>
            <rank>285</rank>
            <popularity>161</popularity>
        </statistics_info>
    </anime>
</anime_catalog>

=== radinan/XML/valid_xml_1.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE anime_catalog SYSTEM "anime_catalog.dtd">

<anime_catalog>
    <anime anime_id="1">
        <main_info>
            <title>Naruto</title>
            <author nationality="Japanese">Masashi Kishimoto</author>
            <genre>Action, Adventure, Comedy</genre>
            <type>Shounen</type>
            <source>Manga</source>
        </main_info>
        <show_info>
            <seasons>
                <season episodes="57">1</season>
                <season episodes="43">2</season>
                <season episodes="41">3</season>
                <season episodes="42">4</season>
                <season episodes="37">5</season>
            </seasons>
            <all_episodes>220</all_episodes>
            <duration unit="minutes">23</duration>
        </show_info>
        <publish_info>
            <aired>
                <begin>3 Oct 2002</begin>
                <end>8 Feb 2007</end>
            </aired>
            <premiered season="Fall">2002</premiered>
            <studio>Studio Pierrot</studio>
            <producers>TV Tokyo, Aniplex, Shueisha</producers>
            <licensors>VIZ Media</licensors>
        </publish_info>
        <statistics_info>
            <score>7.96</score>
            <rank>615</rank>
            <popularity>7</popularity>
        </statistics_info>
    </anime>
</anime_catalog>
